In [1]:
import numpy as np

In [2]:
from sklearn.svm import LinearSVC

In [3]:
from sklearn import cross_validation

In [4]:
from sklearn.learning_curve import learning_curve

In [5]:
import matplotlib.pyplot as plt

In [6]:
clf = LinearSVC()

In [7]:
data = np.loadtxt("q3_data.csv", delimiter =",")

In [8]:
data

array([[-1.06377997,  0.67640868,  1.06935647, ...,  1.05721416,
        -0.90259159,  0.        ],
       [ 0.0708476 , -1.69528125,  2.44944917, ..., -0.37566904,
        -0.62323644,  1.        ],
       [ 0.94028404, -0.49214582,  0.67795602, ...,  1.35904607,
        -1.18958963,  1.        ],
       ..., 
       [-0.5348271 , -0.74645927,  0.86505187, ...,  0.2509557 ,
        -0.9348867 ,  1.        ],
       [-1.03042542, -0.29607249,  2.78034649, ..., -0.14987096,
         2.78960064,  0.        ],
       [ 0.54272502,  0.30821962,  0.20152656, ...,  0.12630589,
        -1.42647315,  1.        ]])

In [9]:
X = data[:, :20]

In [10]:
X

array([[-1.06377997,  0.67640868,  1.06935647, ..., -0.35562842,
         1.05721416, -0.90259159],
       [ 0.0708476 , -1.69528125,  2.44944917, ...,  0.01708348,
        -0.37566904, -0.62323644],
       [ 0.94028404, -0.49214582,  0.67795602, ..., -0.06946407,
         1.35904607, -1.18958963],
       ..., 
       [-0.5348271 , -0.74645927,  0.86505187, ..., -1.30657958,
         0.2509557 , -0.9348867 ],
       [-1.03042542, -0.29607249,  2.78034649, ...,  0.05398851,
        -0.14987096,  2.78960064],
       [ 0.54272502,  0.30821962,  0.20152656, ...,  1.09537374,
         0.12630589, -1.42647315]])

In [11]:
y = data[:, 20]

In [12]:
y

array([ 0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1

In [13]:
plt.figure("Question 3 Part B")

In [14]:
plt.title("Title")

In [15]:
plt.xlabel("X Label")

In [16]:
plt.ylabel("Y Label")

In [17]:
train_sizes_abs, train_scores, test_scores = learning_curve(LinearSVC(C=10),
X, y, cv=10, n_jobs=4, train_sizes = np.linspace(0.9, 0.1, 25))

In [18]:
print(np.mean(train_scores, axis=1))

[ 1.          1.          1.          0.97486034  0.96842105  0.96276151
  0.96468401  0.96454849  0.96018237  0.95710306  0.95321337  0.95441527
  0.9532294   0.95156576  0.95383104  0.95157699  0.95254833  0.95008347
  0.95214626  0.95189681  0.95050798  0.95146036  0.95140187  0.95263158
  0.95512979]


In [19]:
train_scores_mean = np.mean(train_scores, axis=1)

In [20]:
train_scores_mean

array([ 1.        ,  1.        ,  1.        ,  0.97486034,  0.96842105,
        0.96276151,  0.96468401,  0.96454849,  0.96018237,  0.95710306,
        0.95321337,  0.95441527,  0.9532294 ,  0.95156576,  0.95383104,
        0.95157699,  0.95254833,  0.95008347,  0.95214626,  0.95189681,
        0.95050798,  0.95146036,  0.95140187,  0.95263158,  0.95512979])

In [21]:
train_scores_std = np.std(train_scores, axis=1)

In [22]:
train_scores_std

array([ 0.        ,  0.        ,  0.        ,  0.01037663,  0.01356693,
        0.00758927,  0.00914377,  0.00960047,  0.00534298,  0.00485671,
        0.00648304,  0.0057922 ,  0.00434156,  0.00393903,  0.00483237,
        0.00457846,  0.00342594,  0.00438211,  0.0027027 ,  0.00372008,
        0.00427849,  0.00380638,  0.00439575,  0.00399599,  0.00271097])

In [23]:
test_scores_mean = np.mean(test_scores, axis=1)

In [24]:
test_scores_mean

array([ 0.86291419,  0.85985499,  0.88586589,  0.9169568 ,  0.9229869 ,
        0.9319972 ,  0.9359574 ,  0.94293779,  0.9420077 ,  0.9410176 ,
        0.9420275 ,  0.9420176 ,  0.9459978 ,  0.947998  ,  0.947978  ,
        0.9449877 ,  0.9449879 ,  0.947018  ,  0.9460279 ,  0.945038  ,
        0.943018  ,  0.9460279 ,  0.9460079 ,  0.9460081 ,  0.9449879 ])

In [25]:
test_scores_std = np.std(test_scores, axis=1)

In [26]:
test_scores_std

array([ 0.03017531,  0.03758512,  0.0362364 ,  0.02430369,  0.02243016,
        0.01833628,  0.02168597,  0.01865217,  0.01886542,  0.01917097,
        0.0198671 ,  0.02180199,  0.02016346,  0.01781354,  0.02096823,
        0.01751149,  0.02065479,  0.02239754,  0.02153107,  0.02536864,
        0.02325952,  0.02058123,  0.02011492,  0.02336202,  0.02209626])

In [30]:
plt.grid()

In [31]:
 plt.fill_between(train_sizes_abs, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1,
                     color="r")

In [32]:
 plt.fill_between(train_sizes_abs, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

In [33]:
 plt.plot(train_sizes_abs, train_scores_mean, 'o-', color="r")

In [34]:
plt.plot(train_sizes_abs, test_scores_mean, 'o-', color="g")

In [35]:
plt.show()