In [1]:
import numpy as np

In [2]:
from sklearn.svm import LinearSVC

In [3]:
from sklearn import cross_validation

In [4]:
from sklearn.learning_curve import learning_curve

In [5]:
import matplotlib.pyplot as plt

In [6]:
clf = LinearSVC()

In [7]:
data = np.loadtxt("q3_data.csv", delimiter =",")

In [8]:
data

array([[-1.06377997,  0.67640868,  1.06935647, ...,  1.05721416,
        -0.90259159,  0.        ],
       [ 0.0708476 , -1.69528125,  2.44944917, ..., -0.37566904,
        -0.62323644,  1.        ],
       [ 0.94028404, -0.49214582,  0.67795602, ...,  1.35904607,
        -1.18958963,  1.        ],
       ..., 
       [-0.5348271 , -0.74645927,  0.86505187, ...,  0.2509557 ,
        -0.9348867 ,  1.        ],
       [-1.03042542, -0.29607249,  2.78034649, ..., -0.14987096,
         2.78960064,  0.        ],
       [ 0.54272502,  0.30821962,  0.20152656, ...,  0.12630589,
        -1.42647315,  1.        ]])

In [9]:
X = data[:, :20]

In [10]:
X

array([[-1.06377997,  0.67640868,  1.06935647, ..., -0.35562842,
         1.05721416, -0.90259159],
       [ 0.0708476 , -1.69528125,  2.44944917, ...,  0.01708348,
        -0.37566904, -0.62323644],
       [ 0.94028404, -0.49214582,  0.67795602, ..., -0.06946407,
         1.35904607, -1.18958963],
       ..., 
       [-0.5348271 , -0.74645927,  0.86505187, ..., -1.30657958,
         0.2509557 , -0.9348867 ],
       [-1.03042542, -0.29607249,  2.78034649, ...,  0.05398851,
        -0.14987096,  2.78960064],
       [ 0.54272502,  0.30821962,  0.20152656, ...,  1.09537374,
         0.12630589, -1.42647315]])

In [11]:
y = data[:, 20]

In [12]:
y

array([ 0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1

In [13]:
plt.figure("Question 3 Part A")

In [14]:
plt.title("Title")

In [15]:
plt.xlabel("X Label")

In [16]:
plt.ylabel("Y Label")

In [17]:
train_sizes_abs, train_scores, test_scores = learning_curve(LinearSVC(C=10),
X, y, cv=10, n_jobs=4, train_sizes = np.linspace(0.05, 0.2, 25))

In [18]:
print(np.mean(train_scores, axis=1))

[ 1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  0.99490446  0.99506173  0.99404762  0.97356322  0.97039106]


In [19]:
train_scores_mean = np.mean(train_scores, axis=1)

In [20]:
train_scores_mean

array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        0.99490446,  0.99506173,  0.99404762,  0.97356322,  0.97039106])

In [21]:
train_scores_std = np.std(train_scores, axis=1)

In [22]:
train_scores_std

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.00254777,  0.00246914,  0.00376462,  0.01364867,  0.01250449])

In [23]:
test_scores_mean = np.mean(test_scores, axis=1)

In [24]:
test_scores_mean

array([ 0.8709546 ,  0.86992429,  0.8929958 ,  0.8920057 ,  0.8910156 ,
        0.8540336 ,  0.8560138 ,  0.86294369,  0.86291419,  0.86491439,
        0.85090449,  0.85486489,  0.85184488,  0.85184488,  0.85985499,
        0.87085539,  0.87185519,  0.88187559,  0.88388569,  0.88686589,
        0.88684568,  0.88386549,  0.88384528,  0.9209568 ,  0.91894669])

In [25]:
test_scores_std = np.std(test_scores, axis=1)

In [26]:
test_scores_std

array([ 0.0345781 ,  0.03516158,  0.03139287,  0.02786507,  0.02840257,
        0.03361726,  0.03398997,  0.02648768,  0.03017531,  0.03150156,
        0.03811963,  0.04190126,  0.04208136,  0.04208136,  0.03758512,
        0.0431071 ,  0.03450268,  0.03357227,  0.03421746,  0.03536022,
        0.03423844,  0.03213471,  0.03163766,  0.02447479,  0.0228001 ])

In [27]:
plt.grid()

In [28]:
 plt.fill_between(train_sizes_abs, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1,
                     color="r")

In [29]:
 plt.fill_between(train_sizes_abs, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

In [30]:
 plt.plot(train_sizes_abs, train_scores_mean, 'o-', color="r")

In [31]:
plt.plot(train_sizes_abs, test_scores_mean, 'o-', color="g")

In [32]:
plt.show()